name: LorraineJug
description: Lorraine Java User Group
author: lorrainejug
url: http://www.lorrainejug.fr
logo: /images/logo-carre_200x200.png
exclude: [README.md, _site/]
plugins: [jekyll-paginate, jekyll-seo-tag]
markdown: kramdown
highlighter: rouge
baseurl:
paginate: 5
paginate_path: events/:num
timezone: Europe/Paris
sass:
    sass_dir: css/_sass
    style: compressed             # nested|expanded|compact|compressed
twitter:
  username: lorrainejug
